# Generated by Django 5.2.2 on 2025-06-09 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cid', models.CharField(blank=True, max_length=50, null=True)),
                ('smiles', models.TextField(blank=True, null=True)),
                ('ic50', models.FloatField(blank=True, null=True)),
                ('lelp', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('molecular_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('iupac_name', models.CharField(blank=True, max_length=255, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('inchi', models.TextField(blank=True, null=True)),
                ('inchikey', models.CharField(blank=True, max_length=255, null=True)),
                ('structure_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('training_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('input_source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ml_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mlmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic50', models.FloatField(blank=True, null=True)),
                ('lelp', models.FloatField(blank=True, null=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.compound')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_compounds', to='api.prediction')),
            ],
            options={
                'unique_together': {('prediction', 'compound')},
            },
        ),
    ]
