# Generated by Django 5.1.4 on 2025-01-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_compound_smilescode_compound_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='canonical_smiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='classification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='conjugate_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='inchi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='inchikey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='iupac_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='toxicity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
