# Generated by Django 5.1.4 on 2025-01-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_compound_canonical_smiles_compound_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='structure',
            field=models.URLField(blank=True, null=True),
        ),
    ]
