# Generated by Django 5.1.4 on 2025-02-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_classification_compound_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='iupac_name',
        ),
        migrations.AddField(
            model_name='compound',
            name='iupac_namye',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
