# Generated by Django 5.1.4 on 2025-02-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_compound_iupac_name_compound_iupac_namye_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='iupac_namye',
            new_name='iupac_name',
        ),
    ]
