# Generated by Django 5.1.4 on 2025-02-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_compound_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='cid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
