# Generated by Django 5.1.4 on 2025-02-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_compound_cid_alter_compound_smiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchikey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='iupac_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
