# Generated by Django 5.1.4 on 2025-04-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_prediction_id_compound_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='model_descriptor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
