# Generated by Django 5.1.4 on 2025-04-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mlmodel_model_descriptor_mlmodel_model_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='model_descriptor',
            new_name='descriptor',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='model_method',
            new_name='method',
        ),
    ]
